# Generated by Django 3.2.9 on 2021-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('kakao_id', models.CharField(max_length=40)),
                ('nick_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
