# Generated by Django 3.2.9 on 2021-11-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('introduction', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=13)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=13)),
                ('phone_number', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'accomodations',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('max_people', models.IntegerField()),
                ('min_people', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_bed', models.IntegerField()),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodations.accomodation')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField()),
                ('image', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'room_images',
            },
        ),
        migrations.CreateModel(
            name='RoomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodations.option')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodations.room')),
            ],
            options={
                'db_table': 'room_options',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='option',
            field=models.ManyToManyField(related_name='rooms', through='accomodations.RoomOption', to='accomodations.Option'),
        ),
        migrations.CreateModel(
            name='AccomodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accomodations.accomodation')),
            ],
            options={
                'db_table': 'accomodation_images',
            },
        ),
        migrations.AddField(
            model_name='accomodation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodations.category'),
        ),
    ]
