# Generated by Django 3.2.9 on 2021-11-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0002_alter_roomimage_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
