# Generated by Django 3.2.9 on 2021-11-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0003_rename_image_roomimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodationimage',
            old_name='url',
            new_name='image_url',
        ),
    ]
