# Generated by Django 3.2.9 on 2021-11-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('accomodations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'payment_types',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('number_of_adult', models.IntegerField()),
                ('user_request', models.CharField(max_length=200, null=True)),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodations.accomodation')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.paymenttype')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodations.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
